"""Argument schema for bounded external integrations and operator controls."""
from __future__ import annotations

import argparse
from pathlib import Path


def add_integration_commands(commands: argparse._SubParsersAction) -> None:
    browser = commands.add_parser(
        "browser",
        help="Configure bounded access to an already-running local Chrome DevTools endpoint.",
    )
    browser_commands = browser.add_subparsers(dest="browser_command", required=True)
    browser_status = browser_commands.add_parser("status", help="Show local browser-read readiness without connecting to Chrome.")
    browser_status.add_argument("--json", action="store_true")
    browser_configure = browser_commands.add_parser("configure", help="Replace only the non-secret [browser] configuration.")
    browser_configure.add_argument("--node-command", type=Path, required=True)
    browser_configure.add_argument("--cdp-endpoint", required=True, help="Loopback Chrome DevTools HTTP endpoint, for example http://127.0.0.1:9222")
    browser_configure.add_argument("--timeout-seconds", type=float, default=10.0)
    browser_configure.add_argument("--max-result-bytes", type=int, default=48_000)
    browser_configure.add_argument("--allow-control", action="store_true", help="Enable approval-only navigation, click, and text-entry actions for existing tabs.")
    browser_configure.add_argument("--capture-directory", type=Path, default=None, help="Existing absolute directory for approval-only PNG captures of existing tabs; requires --allow-control.")
    browser_configure.add_argument("--json", action="store_true")
    browser_test = browser_commands.add_parser("test", help="List local browser tabs and optionally read one bounded page snapshot; no Company Job is created.")
    browser_test.add_argument("--tab-index", type=int, default=None)
    browser_test.add_argument("--confirm", action="store_true")
    browser_test.add_argument("--json", action="store_true")
    browser_disable = browser_commands.add_parser("disable", help="Remove only [browser]; it never starts or controls a browser.")
    browser_disable.add_argument("--json", action="store_true")
    browser_launch = browser_commands.add_parser("launch", help="Start one operator-confirmed isolated Chromium-family browser profile and update the configured loopback endpoint.")
    browser_launch.add_argument("--browser-command", dest="browser_executable", type=Path, required=True, help="Absolute Chromium/Chrome/Edge executable path; Noruct never installs a browser.")
    browser_launch.add_argument("--timeout-seconds", type=float, default=8.0)
    browser_launch.add_argument("--confirm", action="store_true")
    browser_launch.add_argument("--json", action="store_true")
    browser_close = browser_commands.add_parser("close", help="Close only the isolated browser process previously launched by Noruct and delete its temporary profile.")
    browser_close.add_argument("--confirm", action="store_true")
    browser_close.add_argument("--json", action="store_true")
    computer_use = commands.add_parser(
        "computer-use",
        help="Configure one approval-gated local desktop capability through a user-managed CUA driver.",
    )
    computer_use_commands = computer_use.add_subparsers(dest="computer_use_command", required=True)
    computer_use_status = computer_use_commands.add_parser("status", help="Show local computer-use readiness without opening or controlling an application.")
    computer_use_status.add_argument("--json", action="store_true")
    computer_use_configure = computer_use_commands.add_parser("configure", help="Replace only the non-secret [computer_use] policy.")
    computer_use_configure.add_argument("--driver-command", type=Path, required=True)
    computer_use_configure.add_argument("--allow-app", action="append", required=True, help="One exact app name or bundle identifier; repeat up to eight times.")
    computer_use_configure.add_argument("--timeout-seconds", type=float, default=20.0)
    computer_use_configure.add_argument("--max-result-bytes", type=int, default=48_000)
    computer_use_configure.add_argument("--allow-control", action="store_true", help="Allow per-action approved desktop controls after a capture.")
    computer_use_configure.add_argument("--json", action="store_true")
    computer_use_test = computer_use_commands.add_parser("test", help="Capture one configured application after explicit confirmation; no Company Job is created.")
    computer_use_test.add_argument("--app", required=True)
    computer_use_test.add_argument("--confirm", action="store_true")
    computer_use_test.add_argument("--json", action="store_true")
    computer_use_preflight = computer_use_commands.add_parser(
        "preflight",
        help="List only configured allowed desktop applications through the user-managed driver; it captures no screen and starts no Company Job.",
    )
    computer_use_preflight.add_argument("--confirm", action="store_true")
    computer_use_preflight.add_argument("--json", action="store_true")
    computer_use_disable = computer_use_commands.add_parser("disable", help="Remove only [computer_use]; it never changes the driver or desktop.")
    computer_use_disable.add_argument("--json", action="store_true")
    media = commands.add_parser(
        "media",
        help="Configure approval-gated direct image, speech, transcription, and video tools.",
    )
    media_commands = media.add_subparsers(dest="media_command", required=True)
    media_status = media_commands.add_parser("status", help="Show media capability readiness without calling an external service.")
    media_status.add_argument("--json", action="store_true")
    media_configure = media_commands.add_parser("configure", help="Replace only the non-secret [openai_media] policy.")
    media_configure.add_argument("--api-key-env", default="OPENAI_API_KEY")
    media_configure.add_argument("--enable", action="append", required=True, choices=("image", "speech", "transcription", "video"), help="Enable one bounded media capability; repeatable.")
    media_configure.add_argument("--image-model", default="gpt-image-2")
    media_configure.add_argument("--speech-model", default="gpt-4o-mini-tts")
    media_configure.add_argument("--transcription-model", default="gpt-4o-mini-transcribe")
    media_configure.add_argument("--video-model", default="sora-2")
    media_configure.add_argument("--timeout-seconds", type=float, default=90.0)
    media_configure.add_argument("--video-timeout-seconds", type=float, default=600.0)
    media_configure.add_argument("--json", action="store_true")
    media_disable = media_commands.add_parser("disable", help="Remove only [openai_media]; no external media request is made.")
    media_disable.add_argument("--json", action="store_true")
    web_search = commands.add_parser("web-search", help="Configure a bounded search tool against one user-managed SearXNG endpoint.")
    web_search_commands = web_search.add_subparsers(dest="web_search_command", required=True)
    web_search_status = web_search_commands.add_parser("status", help="Show SearXNG search readiness without contacting the endpoint.")
    web_search_status.add_argument("--json", action="store_true")
    web_search_configure = web_search_commands.add_parser("configure", help="Replace only the non-secret [web_search] policy.")
    web_search_configure.add_argument("--base-url", required=True, help="One HTTPS SearXNG instance URL, or explicit loopback HTTP URL.")
    web_search_configure.add_argument("--timeout-seconds", type=float, default=10.0)
    web_search_configure.add_argument("--max-results", type=int, default=5)
    web_search_configure.add_argument("--max-result-bytes", type=int, default=32_000)
    web_search_configure.add_argument("--json", action="store_true")
    web_search_disable = web_search_commands.add_parser("disable", help="Remove only [web_search]; it never contacts the configured endpoint.")
    web_search_disable.add_argument("--json", action="store_true")
    home_assistant = commands.add_parser("home-assistant", help="Configure allowlisted Home Assistant REST tools behind individual approvals.")
    home_assistant_commands = home_assistant.add_subparsers(dest="home_assistant_command", required=True)
    home_assistant_status = home_assistant_commands.add_parser("status", help="Show Home Assistant readiness without contacting the instance.")
    home_assistant_status.add_argument("--json", action="store_true")
    home_assistant_configure = home_assistant_commands.add_parser("configure", help="Configure one Home Assistant instance and explicit entity/service allowlists; it never contacts the instance.")
    home_assistant_configure.add_argument("--base-url", required=True)
    home_assistant_configure.add_argument("--token-env", default="HASS_TOKEN")
    home_assistant_configure.add_argument("--allow-entity", action="append", required=True, help="Allowed entity ID or bounded wildcard, repeatable.")
    home_assistant_configure.add_argument("--allow-service", action="append", default=[], help="Allowed domain.service action, repeatable; blocked execution domains are rejected.")
    home_assistant_configure.add_argument("--timeout-seconds", type=float, default=15.0)
    home_assistant_configure.add_argument("--max-result-bytes", type=int, default=32_000)
    home_assistant_configure.add_argument("--json", action="store_true")
    home_assistant_disable = home_assistant_commands.add_parser("disable", help="Remove only [home_assistant]; no request is made.")
    home_assistant_disable.add_argument("--json", action="store_true")
    plugin = commands.add_parser("plugin", help="Stage and explicitly enable bounded out-of-process executable plugins.")
    plugin_commands = plugin.add_subparsers(dest="plugin_command", required=True)
    plugin_status = plugin_commands.add_parser("status", help="Show executable-plugin runtime status without loading or running a plugin.")
    plugin_status.add_argument("--json", action="store_true")
    plugin_list = plugin_commands.add_parser("list", help="List installed executable plugin versions without running them.")
    plugin_list.add_argument("--json", action="store_true")
    plugin_history = plugin_commands.add_parser(
        "history",
        help="Show bounded, content-free executable-plugin lifecycle receipts without loading or running a plugin.",
    )
    plugin_history.add_argument("plugin_id", nargs="?", default=None)
    plugin_history.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_history.add_argument("--limit", type=int, default=20)
    plugin_history.add_argument("--json", action="store_true")
    plugin_install = plugin_commands.add_parser("install", help="Copy one local plugin package into the Noruct-managed plugin store as an inactive exact version.")
    plugin_install.add_argument("source", type=Path, help="Local directory containing noruct-plugin.json and its executable host.")
    plugin_install.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_install.add_argument("--confirm", action="store_true")
    plugin_install.add_argument("--json", action="store_true")
    plugin_install_git = plugin_commands.add_parser("install-git", help="Stage one exact HTTPS Git commit as an inactive reviewed plugin package.")
    plugin_install_git.add_argument("--url", required=True, help="HTTPS Git repository URL without credentials.")
    plugin_install_git.add_argument("--commit", required=True, help="Exact 40-character Git commit; branches and tags are not accepted.")
    plugin_install_git.add_argument("--subdirectory", default="", help="Relative plugin directory inside the checked-out repository.")
    plugin_install_git.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_install_git.add_argument("--confirm", action="store_true")
    plugin_install_git.add_argument("--json", action="store_true")
    plugin_update_check = plugin_commands.add_parser("update-check", help="Resolve one Git ref for an installed Git-backed plugin without installing or activating it.")
    plugin_update_check.add_argument("plugin_id")
    plugin_update_check.add_argument("--ref", required=True, help="Exact remote refs/heads/* or refs/tags/* name to inspect; it is never installed as a mutable source.")
    plugin_update_check.add_argument("--version", default=None, help="Installed Git-backed version to compare; defaults to the active version, then latest installed.")
    plugin_update_check.add_argument("--confirm", action="store_true")
    plugin_update_check.add_argument("--json", action="store_true")
    plugin_catalog_fetch = plugin_commands.add_parser("catalog-fetch", help="Fetch and stage one signed HTTPS plugin catalog; it never installs or runs plugin code.")
    plugin_catalog_fetch.add_argument("--url", required=True, help="Credential-free HTTPS URL of canonical catalog JSON.")
    plugin_catalog_fetch.add_argument("--signature-url", required=True, help="Credential-free HTTPS URL of the detached OpenSSH signature.")
    plugin_catalog_fetch.add_argument("--allowed-signers", required=True, type=Path, help="Local OpenSSH allowed-signers file.")
    plugin_catalog_fetch.add_argument("--principal", required=True, help="Expected OpenSSH signer principal.")
    plugin_catalog_fetch.add_argument("--ssh-keygen", required=True, type=Path, help="Absolute user-managed ssh-keygen verifier path.")
    plugin_catalog_fetch.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_catalog_fetch.add_argument("--confirm", action="store_true")
    plugin_catalog_fetch.add_argument("--json", action="store_true")
    plugin_catalog_source_add = plugin_commands.add_parser("catalog-source-add", help="Register one signed catalog origin for later explicit refresh; it does not contact the network or install plugins.")
    plugin_catalog_source_add.add_argument("--catalog-id", required=True)
    plugin_catalog_source_add.add_argument("--url", required=True)
    plugin_catalog_source_add.add_argument("--signature-url", required=True)
    plugin_catalog_source_add.add_argument("--allowed-signers", required=True, type=Path)
    plugin_catalog_source_add.add_argument("--principal", required=True)
    plugin_catalog_source_add.add_argument("--ssh-keygen", required=True, type=Path)
    plugin_catalog_source_add.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_catalog_source_add.add_argument("--confirm", action="store_true")
    plugin_catalog_source_add.add_argument("--json", action="store_true")
    plugin_catalog_source_list = plugin_commands.add_parser("catalog-source-list", help="List locally registered signed catalog origins without contacting them.")
    plugin_catalog_source_list.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_catalog_source_list.add_argument("--json", action="store_true")
    plugin_catalog_source_remove = plugin_commands.add_parser("catalog-source-remove", help="Remove one local catalog origin without contacting it or deleting staged snapshots.")
    plugin_catalog_source_remove.add_argument("catalog_id")
    plugin_catalog_source_remove.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_catalog_source_remove.add_argument("--confirm", action="store_true")
    plugin_catalog_source_remove.add_argument("--json", action="store_true")
    plugin_catalog_refresh = plugin_commands.add_parser("catalog-refresh", help="Fetch and re-verify one registered signed catalog source; it never installs, enables, or runs a plugin.")
    plugin_catalog_refresh.add_argument("catalog_id")
    plugin_catalog_refresh.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_catalog_refresh.add_argument("--confirm", action="store_true")
    plugin_catalog_refresh.add_argument("--json", action="store_true")
    plugin_catalog_list = plugin_commands.add_parser("catalog-list", help="List locally staged signed plugin catalogs without contacting a network or running plugins.")
    plugin_catalog_list.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_catalog_list.add_argument("--json", action="store_true")
    plugin_catalog_candidates = plugin_commands.add_parser(
        "catalog-candidates",
        help="Compare staged signed catalog entries with local plugin receipts; no network, install, enable, or execution occurs.",
    )
    plugin_catalog_candidates.add_argument("--catalog-id", default=None, help="Limit the local comparison to one staged catalog id.")
    plugin_catalog_candidates.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_catalog_candidates.add_argument("--json", action="store_true")
    plugin_catalog_install = plugin_commands.add_parser("catalog-install", help="Install one exact Git commit from a verified staged catalog as inactive.")
    plugin_catalog_install.add_argument("catalog_id")
    plugin_catalog_install.add_argument("plugin_id")
    plugin_catalog_install.add_argument("--version", default=None, help="Exact catalog version; omit only when the catalog has one match.")
    plugin_catalog_install.add_argument("--catalog-digest", default=None, help="Exact reviewed staged catalog digest; required when more than one snapshot exists for the catalog ID.")
    plugin_catalog_install.add_argument("--root", type=Path, default=None, help="Managed plugin root (default: sibling plugins directory beside the config file).")
    plugin_catalog_install.add_argument("--confirm", action="store_true")
    plugin_catalog_install.add_argument("--json", action="store_true")
    plugin_environment_build = plugin_commands.add_parser(
        "environment-build",
        help="Build one plugin version's hash-locked dependency environment; it never runs plugin code.",
    )
    plugin_environment_build.add_argument("plugin_id")
    plugin_environment_build.add_argument("--version", default=None, help="Exact installed version; omit only to select the latest staged version.")
    plugin_environment_build.add_argument("--python", dest="python_command", default=None, help="Python executable used only to create this isolated environment.")
    plugin_environment_build.add_argument("--confirm", action="store_true")
    plugin_environment_build.add_argument("--json", action="store_true")
    plugin_enable = plugin_commands.add_parser("enable", help="Enable a reviewed installed plugin version; calls remain individually approved.")
    plugin_enable.add_argument("plugin_id")
    plugin_enable.add_argument("--version", default=None, help="Exact already-installed version; omit only to select the latest staged version.")
    plugin_enable.add_argument("--confirm", action="store_true")
    plugin_enable.add_argument("--json", action="store_true")
    plugin_disable = plugin_commands.add_parser("disable", help="Disable one plugin without deleting its installed package.")
    plugin_disable.add_argument("plugin_id")
    plugin_disable.add_argument("--confirm", action="store_true")
    plugin_disable.add_argument("--json", action="store_true")
    plugin_remove = plugin_commands.add_parser("remove", help="Withdraw all plugin versions from future Jobs; exact managed bytes remain for already assembled Jobs.")
    plugin_remove.add_argument("plugin_id")
    plugin_remove.add_argument("--confirm", action="store_true")
    plugin_remove.add_argument("--json", action="store_true")
    plugin_rollback = plugin_commands.add_parser("rollback", help="Activate the immediately preceding installed version of one enabled plugin.")
    plugin_rollback.add_argument("plugin_id")
    plugin_rollback.add_argument("--confirm", action="store_true")
    plugin_rollback.add_argument("--json", action="store_true")
    plugin_runtime_disable = plugin_commands.add_parser("runtime-disable", help="Disable all executable plugins by removing [plugins]; packages remain installed.")
    plugin_runtime_disable.add_argument("--json", action="store_true")
    capabilities = commands.add_parser("capabilities", help="Inspect the configured optional capability surface and its explicit setup commands.")
    capabilities_commands = capabilities.add_subparsers(dest="capabilities_command", required=True)
    capabilities_status = capabilities_commands.add_parser("status", help="Show provider, context, browser, web-read, channel, and remote-worker readiness without invoking them.")
    capabilities_status.add_argument("--json", action="store_true")
    capabilities_guide = capabilities_commands.add_parser(
        "guide",
        help="Show one grouped extension lifecycle and the next local setup command for Skills, MCP, and plugins.",
    )
    capabilities_guide.add_argument("--json", action="store_true")
    tools = commands.add_parser(
        "tools",
        help="Show optional Noruct tool connections and their explicit setup commands.",
    )
    tools_commands = tools.add_subparsers(dest="tools_command", required=True)
    tools_status = tools_commands.add_parser(
        "status",
        help="Show provider, context, browser, web-read, channel, and remote-worker readiness without invoking them.",
    )
    tools_status.add_argument("--json", action="store_true")
    environment = commands.add_parser(
        "environment",
        help="Inspect local execution or configure an explicit, approval-gated remote Company worker.",
    )
    environment_commands = environment.add_subparsers(dest="environment_command", required=True)
    environment_status = environment_commands.add_parser(
        "status", help="Show local command, shadow-workspace, and remote-execution readiness without mutation or network access."
    )
    environment_status.add_argument("--workspace", type=Path, default=Path.cwd())
    environment_status.add_argument("--json", action="store_true")
    environment_snapshot = environment_commands.add_parser(
        "snapshot",
        help="Write one local content-hash workspace manifest for future remote-adapter review; it never uploads files or starts a Job.",
    )
    environment_snapshot.add_argument("--workspace", type=Path, default=Path.cwd())
    environment_snapshot.add_argument("--output", type=Path, required=True)
    environment_snapshot.add_argument("--confirm", action="store_true")
    environment_snapshot.add_argument("--json", action="store_true")
    environment_snapshot_inspect = environment_commands.add_parser(
        "snapshot-inspect",
        help="Validate one local workspace-handoff manifest without reading workspace files, SSH, upload, or a Company Job.",
    )
    environment_snapshot_inspect.add_argument("--source", type=Path, required=True)
    environment_snapshot_inspect.add_argument("--json", action="store_true")
    environment_transfer = environment_commands.add_parser(
        "ssh-transfer",
        help="Upload one confirmed, hash-verified workspace snapshot to an isolated SSH staging directory; it never starts a Company Job.",
    )
    environment_transfer.add_argument("--workspace", type=Path, required=True)
    environment_transfer.add_argument("--snapshot", type=Path, required=True)
    environment_transfer.add_argument("--host", required=True)
    environment_transfer.add_argument("--user", required=True)
    environment_transfer.add_argument("--port", type=int, default=22)
    environment_transfer.add_argument("--identity-file", type=Path, default=None)
    environment_transfer.add_argument("--remote-workspace", required=True)
    environment_transfer.add_argument("--timeout-seconds", type=float, default=120.0)
    environment_transfer.add_argument("--confirm", action="store_true")
    environment_transfer.add_argument("--json", action="store_true")
    environment_probe = environment_commands.add_parser(
        "ssh-probe", help="Run one fixed-marker SSH reachability probe; it cannot run a Noruct Job."
    )
    environment_probe.add_argument("--host", required=True)
    environment_probe.add_argument("--user", required=True)
    environment_probe.add_argument("--port", type=int, default=22)
    environment_probe.add_argument("--identity-file", type=Path, default=None)
    environment_probe.add_argument("--timeout-seconds", type=float, default=10.0)
    environment_probe.add_argument("--confirm", action="store_true")
    environment_probe.add_argument("--json", action="store_true")
    environment_operator_command = environment_commands.add_parser(
        "ssh-command",
        help="Run one explicitly confirmed operator command in an existing remote workspace; it never creates a Company Job.",
    )
    environment_operator_command.add_argument("--host", required=True)
    environment_operator_command.add_argument("--user", required=True)
    environment_operator_command.add_argument("--port", type=int, default=22)
    environment_operator_command.add_argument("--identity-file", type=Path, default=None)
    environment_operator_command.add_argument("--remote-workspace", required=True)
    environment_operator_command.add_argument("--program", required=True)
    environment_operator_command.add_argument("--arg", action="append", default=[])
    environment_operator_command.add_argument("--timeout-seconds", type=float, default=60.0)
    environment_operator_command.add_argument("--confirm", action="store_true")
    environment_operator_command.add_argument("--json", action="store_true")
    environment_worker_status = environment_commands.add_parser(
        "worker-status",
        help="Show whether a remote Company worker is configured; it makes no connection and starts no Job.",
    )
    environment_worker_status.add_argument("--json", action="store_true")
    environment_worker_verify = environment_commands.add_parser(
        "worker-verify",
        help="Run one confirmed fixed-marker SSH check that the configured receipt-bound snapshot remains present; it never starts a Company Job or remote program.",
    )
    environment_worker_verify.add_argument("--confirm", action="store_true")
    environment_worker_verify.add_argument("--json", action="store_true")
    environment_worker_audit = environment_commands.add_parser(
        "worker-audit",
        help="Re-check the retained transfer SHA-256 ledger for the configured remote snapshot; it never starts a Company Job or remote program.",
    )
    environment_worker_audit.add_argument("--confirm", action="store_true")
    environment_worker_audit.add_argument("--json", action="store_true")
    environment_worker_configure = environment_commands.add_parser(
        "worker-configure",
        help="Replace the non-secret remote worker allowlist using one verified SSH-transfer receipt; it makes no connection.",
    )
    environment_worker_configure.add_argument("--target-id", required=True)
    environment_worker_configure.add_argument("--receipt", type=Path, required=True)
    environment_worker_configure.add_argument(
        "--program",
        action="append",
        default=[],
        metavar="ID=/absolute/program",
        help="Repeat for each remote program the Company may propose; arbitrary remote shell commands are never enabled.",
    )
    environment_worker_configure.add_argument("--identity-file", type=Path, default=None)
    environment_worker_configure.add_argument("--timeout-seconds", type=float, default=120.0)
    environment_worker_configure.add_argument("--json", action="store_true")
    environment_worker_disable = environment_commands.add_parser(
        "worker-disable",
        help="Remove only remote-worker configuration; it never contacts the configured host.",
    )
    environment_worker_disable.add_argument("--json", action="store_true")
    environment_container_status = environment_commands.add_parser(
        "container-status",
        help="Show the configured local container workspace without starting Docker or a Company Job.",
    )
    environment_container_status.add_argument("--json", action="store_true")
    environment_container_verify = environment_commands.add_parser(
        "container-verify",
        help="Run a confirmed local Docker engine/image metadata preflight; it never pulls an image, starts a container, or creates a Company Job.",
    )
    environment_container_verify.add_argument("--confirm", action="store_true")
    environment_container_verify.add_argument("--json", action="store_true")
    environment_preflight = environment_commands.add_parser(
        "preflight",
        help="Run confirmed remote-ledger and local-container metadata checks for configured execution environments; it starts no Job, program, or container.",
    )
    environment_preflight.add_argument("--confirm", action="store_true")
    environment_preflight.add_argument("--json", action="store_true")
    environment_container_configure = environment_commands.add_parser(
        "container-configure",
        help="Configure one local Docker image and exact command allowlist; it never starts a container.",
    )
    environment_container_configure.add_argument("--image", required=True, help="Immutable or tagged local/container-registry image reference.")
    environment_container_configure.add_argument(
        "--program", action="append", default=[], metavar="ID=COMMAND",
        help="Repeat for each exact program in the image, for example tests=/usr/bin/pytest. Shell strings are not enabled.",
    )
    environment_container_configure.add_argument("--docker-command", default="docker")
    environment_container_configure.add_argument("--timeout-seconds", type=float, default=120.0)
    environment_container_configure.add_argument("--memory-limit-mb", type=int, default=2048)
    environment_container_configure.add_argument("--cpu-limit", type=float, default=2.0)
    environment_container_configure.add_argument("--pids-limit", type=int, default=256)
    environment_container_configure.add_argument("--max-output-bytes", type=int, default=64_000)
    environment_container_configure.add_argument("--json", action="store_true")
    environment_container_disable = environment_commands.add_parser(
        "container-disable",
        help="Remove only [container] configuration; it never contacts or removes a container.",
    )
    environment_container_disable.add_argument("--json", action="store_true")
    channel = commands.add_parser(
        "channel",
        help="Configure bounded user-managed outbound or foreground inbound channel bridges.",
    )
    channel_commands = channel.add_subparsers(dest="channel_command", required=True)
    channel_status_parser = channel_commands.add_parser("status", help="Show channel readiness without starting its process.")
    channel_status_parser.add_argument("--json", action="store_true")
    channel_configure = channel_commands.add_parser("configure", help="Replace only the non-secret [channel] configuration.")
    channel_configure.add_argument("--command", dest="channel_command_path", type=Path, required=True)
    channel_configure.add_argument("--arg", action="append", default=[])
    channel_configure.add_argument("--environment", action="append", default=[])
    channel_configure.add_argument("--timeout-seconds", type=float, default=10.0)
    channel_configure.add_argument("--max-message-bytes", type=int, default=4_000)
    channel_configure.add_argument("--json", action="store_true")
    channel_test = channel_commands.add_parser("test", help="Send one operator-provided test message to the configured bridge.")
    channel_test.add_argument("--message", required=True)
    channel_test.add_argument("--title", default="Noruct channel test")
    channel_test.add_argument("--confirm", action="store_true")
    channel_test.add_argument("--json", action="store_true")
    channel_job_summary = channel_commands.add_parser(
        "job-summary",
        help="Send one explicitly confirmed, terminal ACTIVE JOB metadata summary; no goal, workspace, transcript, or tool output is sent.",
    )
    channel_job_summary.add_argument("job_id")
    channel_job_summary.add_argument("--state", type=Path, default=None)
    channel_job_summary.add_argument("--confirm", action="store_true")
    channel_job_summary.add_argument("--json", action="store_true")
    channel_disable = channel_commands.add_parser("disable", help="Remove only [channel]; no external service is contacted.")
    channel_disable.add_argument("--json", action="store_true")
    inbox_status = channel_commands.add_parser("inbox-status", help="Show inbound channel readiness without starting its process.")
    inbox_status.add_argument("--json", action="store_true")
    inbox_configure = channel_commands.add_parser("inbox-configure", help="Replace only non-secret [inbound_channel] configuration.")
    inbox_configure.add_argument("--source-id", required=True, help="Opaque configured source identity emitted by the bridge.")
    inbox_configure.add_argument("--command", dest="inbox_command_path", type=Path, required=True)
    inbox_configure.add_argument("--workspace", type=Path, required=True, help="Existing workspace used for accepted Company Jobs.")
    inbox_configure.add_argument("--allow-sender", action="append", default=[], help="Opaque sender identity accepted from the bridge; repeat at least once.")
    inbox_configure.add_argument("--arg", action="append", default=[])
    inbox_configure.add_argument("--environment", action="append", default=[])
    inbox_configure.add_argument("--max-message-bytes", type=int, default=4_000)
    inbox_configure.add_argument("--max-messages-per-run", type=int, default=4)
    inbox_configure.add_argument("--json", action="store_true")
    inbox_run = channel_commands.add_parser("inbox-run", help="Run the configured inbound bridge in the foreground and dispatch accepted messages as read-only Company Jobs.")
    inbox_run.add_argument("--state", type=Path, default=None)
    inbox_run.add_argument("--max-seconds", type=float, default=300.0, help="Foreground bridge lifetime (1 through 3600 seconds).")
    inbox_run.add_argument("--max-messages", type=int, default=None, help="Accepted message cap; defaults to configured cap.")
    inbox_run.add_argument("--confirm", action="store_true")
    inbox_run.add_argument("--json", action="store_true")
    inbox_disable = channel_commands.add_parser("inbox-disable", help="Remove only [inbound_channel]; it terminates no process and contacts no external service.")
    inbox_disable.add_argument("--json", action="store_true")
    telegram_status = channel_commands.add_parser("telegram-status", help="Show Telegram channel readiness without contacting Telegram.")
    telegram_status.add_argument("--json", action="store_true")
    telegram_configure = channel_commands.add_parser(
        "telegram-configure",
        help="Configure the non-secret foreground Telegram text channel; it never contacts Telegram.",
    )
    telegram_configure.add_argument("--workspace", type=Path, required=True)
    telegram_configure.add_argument("--allow-sender", action="append", default=[], required=True, help="Telegram numeric sender ID allowed to start a Company Job; repeatable.")
    telegram_configure.add_argument("--token-env", default="TELEGRAM_BOT_TOKEN")
    telegram_configure.add_argument("--api-base-url", default="https://api.telegram.org")
    telegram_configure.add_argument("--max-message-bytes", type=int, default=12_000)
    telegram_configure.add_argument("--max-messages-per-run", type=int, default=8)
    telegram_configure.add_argument("--poll-timeout-seconds", type=int, default=15)
    telegram_configure.add_argument("--json", action="store_true")
    telegram_run = channel_commands.add_parser(
        "telegram-run",
        help="Foreground long-poll an allowlisted Telegram text channel and reply with a bounded terminal Company result.",
    )
    telegram_run.add_argument("--state", type=Path, default=None)
    telegram_run.add_argument("--max-seconds", type=float, default=300.0)
    telegram_run.add_argument("--max-messages", type=int, default=None)
    telegram_run.add_argument("--confirm", action="store_true")
    telegram_run.add_argument("--json", action="store_true")
    telegram_disable = channel_commands.add_parser("telegram-disable", help="Remove only [telegram_channel]; no Telegram request is made.")
    telegram_disable.add_argument("--json", action="store_true")
    slack_status = channel_commands.add_parser("slack-status", help="Show Slack outbound readiness without contacting Slack.")
    slack_status.add_argument("--json", action="store_true")
    slack_configure = channel_commands.add_parser("slack-configure", help="Configure one explicit Slack channel destination; it never contacts Slack.")
    slack_configure.add_argument("--channel-id", required=True)
    slack_configure.add_argument("--token-env", default="SLACK_BOT_TOKEN")
    slack_configure.add_argument("--max-message-bytes", type=int, default=12_000)
    slack_configure.add_argument("--timeout-seconds", type=float, default=15.0)
    slack_configure.add_argument("--json", action="store_true")
    slack_test = channel_commands.add_parser("slack-test", help="Send one explicit Slack text message; no Company Job is created.")
    slack_test.add_argument("--message", required=True)
    slack_test.add_argument("--confirm", action="store_true")
    slack_test.add_argument("--json", action="store_true")
    slack_disable = channel_commands.add_parser("slack-disable", help="Remove only [slack_channel]; no Slack request is made.")
    slack_disable.add_argument("--json", action="store_true")
    slack_inbox_status = channel_commands.add_parser("slack-inbox-status", help="Show Slack Events API receiver readiness without binding a port.")
    slack_inbox_status.add_argument("--json", action="store_true")
    slack_inbox_configure = channel_commands.add_parser(
        "slack-inbox-configure",
        help="Configure the non-secret signed Slack Events API receiver; it never contacts Slack or opens a listener.",
    )
    slack_inbox_configure.add_argument("--workspace", type=Path, required=True)
    slack_inbox_configure.add_argument("--allow-sender", action="append", default=[], required=True, help="Slack user ID allowed to start a Company Job; repeatable.")
    slack_inbox_configure.add_argument("--allow-channel", action="append", default=[], required=True, help="Slack channel ID accepted by the receiver; repeatable.")
    slack_inbox_configure.add_argument("--signing-secret-env", default="SLACK_SIGNING_SECRET")
    slack_inbox_configure.add_argument("--port", type=int, default=3001)
    slack_inbox_configure.add_argument("--request-path", default="/slack/events")
    slack_inbox_configure.add_argument("--max-message-bytes", type=int, default=12_000)
    slack_inbox_configure.add_argument("--max-messages-per-run", type=int, default=8)
    slack_inbox_configure.add_argument("--timestamp-skew-seconds", type=int, default=300)
    slack_inbox_configure.add_argument("--json", action="store_true")
    slack_inbox_run = channel_commands.add_parser(
        "slack-inbox-run",
        help="Run a foreground loopback signed Slack Events receiver and dispatch allowlisted text as read-only Company Jobs.",
    )
    slack_inbox_run.add_argument("--state", type=Path, default=None)
    slack_inbox_run.add_argument("--max-seconds", type=float, default=300.0)
    slack_inbox_run.add_argument("--max-messages", type=int, default=None)
    slack_inbox_run.add_argument("--confirm", action="store_true")
    slack_inbox_run.add_argument("--json", action="store_true")
    slack_inbox_disable = channel_commands.add_parser("slack-inbox-disable", help="Remove only [slack_inbound]; it stops no running receiver and contacts no service.")
    slack_inbox_disable.add_argument("--json", action="store_true")
    discord_status = channel_commands.add_parser("discord-status", help="Show Discord webhook readiness without contacting Discord.")
    discord_status.add_argument("--json", action="store_true")
    discord_configure = channel_commands.add_parser("discord-configure", help="Configure one Discord incoming webhook environment name; it never contacts Discord.")
    discord_configure.add_argument("--webhook-env", default="DISCORD_WEBHOOK_URL")
    discord_configure.add_argument("--max-message-bytes", type=int, default=8_000)
    discord_configure.add_argument("--timeout-seconds", type=float, default=15.0)
    discord_configure.add_argument("--json", action="store_true")
    discord_test = channel_commands.add_parser("discord-test", help="Send one explicit Discord webhook text message; no Company Job is created.")
    discord_test.add_argument("--message", required=True)
    discord_test.add_argument("--confirm", action="store_true")
    discord_test.add_argument("--json", action="store_true")
    discord_disable = channel_commands.add_parser("discord-disable", help="Remove only [discord_channel]; no Discord request is made.")
    discord_disable.add_argument("--json", action="store_true")
    discord_inbox_status = channel_commands.add_parser("discord-inbox-status", help="Show bounded Discord text receiver readiness without connecting to Discord.")
    discord_inbox_status.add_argument("--json", action="store_true")
    discord_inbox_configure = channel_commands.add_parser(
        "discord-inbox-configure",
        help="Configure foreground Discord text intake; it never contacts Discord or starts a Gateway session.",
    )
    discord_inbox_configure.add_argument("--workspace", type=Path, required=True)
    discord_inbox_configure.add_argument("--allow-sender", action="append", default=[], required=True, help="Numeric Discord user ID allowed to start a Company Job; repeatable.")
    discord_inbox_configure.add_argument("--allow-channel", action="append", default=[], required=True, help="Numeric Discord channel ID accepted by the receiver; repeatable.")
    discord_inbox_configure.add_argument("--token-env", default="DISCORD_BOT_TOKEN")
    discord_inbox_configure.add_argument("--max-message-bytes", type=int, default=12_000)
    discord_inbox_configure.add_argument("--max-messages-per-run", type=int, default=8)
    discord_inbox_configure.add_argument("--json", action="store_true")
    discord_inbox_run = channel_commands.add_parser(
        "discord-inbox-run",
        help="Run one foreground allowlisted Discord text session and dispatch accepted messages as read-only Company Jobs.",
    )
    discord_inbox_run.add_argument("--state", type=Path, default=None)
    discord_inbox_run.add_argument("--max-seconds", type=float, default=300.0)
    discord_inbox_run.add_argument("--max-messages", type=int, default=None)
    discord_inbox_run.add_argument("--confirm", action="store_true")
    discord_inbox_run.add_argument("--json", action="store_true")
    discord_inbox_disable = channel_commands.add_parser("discord-inbox-disable", help="Remove only [discord_inbound]; it stops no running receiver and contacts no service.")
    discord_inbox_disable.add_argument("--json", action="store_true")
    ntfy_status = channel_commands.add_parser("ntfy-status", help="Show ntfy publish readiness without contacting ntfy.")
    ntfy_status.add_argument("--json", action="store_true")
    ntfy_configure = channel_commands.add_parser("ntfy-configure", help="Configure one ntfy publish topic; it never contacts ntfy.")
    ntfy_configure.add_argument("--topic", required=True, help="Private or user-owned ntfy topic used for one explicit publish.")
    ntfy_configure.add_argument("--server-url", default="https://ntfy.sh")
    ntfy_configure.add_argument("--token-env", default=None, help="Optional environment variable holding a Bearer token or user:password basic credential.")
    ntfy_configure.add_argument("--max-message-bytes", type=int, default=4_000)
    ntfy_configure.add_argument("--timeout-seconds", type=float, default=15.0)
    ntfy_configure.add_argument("--markdown", action="store_true")
    ntfy_configure.add_argument("--json", action="store_true")
    ntfy_test = channel_commands.add_parser("ntfy-test", help="Send one explicit ntfy text message; no Company Job is created.")
    ntfy_test.add_argument("--message", required=True)
    ntfy_test.add_argument("--title", default="Noruct channel test")
    ntfy_test.add_argument("--confirm", action="store_true")
    ntfy_test.add_argument("--json", action="store_true")
    ntfy_disable = channel_commands.add_parser("ntfy-disable", help="Remove only [ntfy_channel]; no ntfy request is made.")
    ntfy_disable.add_argument("--json", action="store_true")
    ntfy_inbox_status = channel_commands.add_parser("ntfy-inbox-status", help="Show ntfy inbound readiness without connecting.")
    ntfy_inbox_status.add_argument("--json", action="store_true")
    ntfy_inbox_configure = channel_commands.add_parser("ntfy-inbox-configure", help="Configure a foreground ntfy JSON-stream receiver; it never connects.")
    ntfy_inbox_configure.add_argument("--workspace", type=Path, required=True)
    ntfy_inbox_configure.add_argument("--topic", required=True)
    ntfy_inbox_configure.add_argument("--server-url", default="https://ntfy.sh")
    ntfy_inbox_configure.add_argument("--token-env", default=None)
    ntfy_inbox_configure.add_argument("--max-message-bytes", type=int, default=4_000)
    ntfy_inbox_configure.add_argument("--max-messages-per-run", type=int, default=4)
    ntfy_inbox_configure.add_argument("--json", action="store_true")
    ntfy_inbox_run = channel_commands.add_parser("ntfy-inbox-run", help="Foreground subscribe to one ntfy topic and dispatch text as read-only Company Jobs.")
    ntfy_inbox_run.add_argument("--state", type=Path, default=None)
    ntfy_inbox_run.add_argument("--max-seconds", type=float, default=300.0)
    ntfy_inbox_run.add_argument("--max-messages", type=int, default=None)
    ntfy_inbox_run.add_argument("--confirm", action="store_true")
    ntfy_inbox_run.add_argument("--json", action="store_true")
    ntfy_inbox_disable = channel_commands.add_parser("ntfy-inbox-disable", help="Remove only [ntfy_inbound]; it contacts no service.")
    ntfy_inbox_disable.add_argument("--json", action="store_true")
    email_status = channel_commands.add_parser("email-status", help="Show SMTP outbound readiness without contacting the server.")
    email_status.add_argument("--json", action="store_true")
    email_configure = channel_commands.add_parser("email-configure", help="Configure one sender and recipient allowlist; it never contacts SMTP.")
    email_configure.add_argument("--sender", required=True, help="One sender address owned by the operator.")
    email_configure.add_argument("--to", action="append", required=True, help="Allowlisted recipient address; repeat up to 16 times.")
    email_configure.add_argument("--smtp-host", required=True)
    email_configure.add_argument("--smtp-port", type=int, default=587, help="465 uses implicit TLS; all other ports use STARTTLS.")
    email_configure.add_argument("--password-env", default="EMAIL_PASSWORD")
    email_configure.add_argument("--username-env", default=None, help="Optional SMTP username environment variable; sender is used when omitted.")
    email_configure.add_argument("--max-message-bytes", type=int, default=40_000)
    email_configure.add_argument("--timeout-seconds", type=float, default=20.0)
    email_configure.add_argument("--json", action="store_true")
    email_test = channel_commands.add_parser("email-test", help="Send one explicit allowlisted SMTP email; no Company Job is created.")
    email_test.add_argument("--subject", default="Noruct channel test")
    email_test.add_argument("--message", required=True)
    email_test.add_argument("--confirm", action="store_true")
    email_test.add_argument("--json", action="store_true")
    email_disable = channel_commands.add_parser("email-disable", help="Remove only [email_channel]; no SMTP request is made.")
    email_disable.add_argument("--json", action="store_true")
    email_inbox_status = channel_commands.add_parser("email-inbox-status", help="Show IMAP inbound readiness without contacting the server.")
    email_inbox_status.add_argument("--json", action="store_true")
    email_inbox_configure = channel_commands.add_parser("email-inbox-configure", help="Configure foreground allowlisted IMAP plaintext intake; it never contacts the mailbox.")
    email_inbox_configure.add_argument("--workspace", type=Path, required=True)
    email_inbox_configure.add_argument("--mailbox", required=True, help="Mailbox address owned by the operator.")
    email_inbox_configure.add_argument("--imap-host", required=True)
    email_inbox_configure.add_argument("--imap-port", type=int, default=993)
    email_inbox_configure.add_argument("--allow-sender", action="append", default=[], required=True, help="Allowed email sender address; repeatable.")
    email_inbox_configure.add_argument("--password-env", default="EMAIL_PASSWORD")
    email_inbox_configure.add_argument("--username-env", default=None)
    email_inbox_configure.add_argument("--folder", default="INBOX")
    email_inbox_configure.add_argument("--max-message-bytes", type=int, default=16_000)
    email_inbox_configure.add_argument("--max-messages-per-run", type=int, default=4)
    email_inbox_configure.add_argument("--timeout-seconds", type=float, default=30.0)
    email_inbox_configure.add_argument("--json", action="store_true")
    email_inbox_run = channel_commands.add_parser("email-inbox-run", help="Read one foreground IMAP unseen-mail batch and dispatch allowlisted plaintext as read-only Company Jobs.")
    email_inbox_run.add_argument("--state", type=Path, default=None)
    email_inbox_run.add_argument("--max-seconds", type=float, default=300.0)
    email_inbox_run.add_argument("--max-messages", type=int, default=None)
    email_inbox_run.add_argument("--confirm", action="store_true")
    email_inbox_run.add_argument("--json", action="store_true")
    email_inbox_disable = channel_commands.add_parser("email-inbox-disable", help="Remove only [email_inbound]; no IMAP request is made.")
    email_inbox_disable.add_argument("--json", action="store_true")
    mattermost_status = channel_commands.add_parser("mattermost-status", help="Show Mattermost outbound readiness without contacting Mattermost.")
    mattermost_status.add_argument("--json", action="store_true")
    mattermost_configure = channel_commands.add_parser("mattermost-configure", help="Configure one Mattermost channel destination; it never contacts Mattermost.")
    mattermost_configure.add_argument("--base-url", required=True)
    mattermost_configure.add_argument("--channel-id", required=True)
    mattermost_configure.add_argument("--token-env", default="MATTERMOST_TOKEN")
    mattermost_configure.add_argument("--max-message-bytes", type=int, default=4_000)
    mattermost_configure.add_argument("--timeout-seconds", type=float, default=15.0)
    mattermost_configure.add_argument("--json", action="store_true")
    mattermost_test = channel_commands.add_parser("mattermost-test", help="Send one explicit Mattermost text message; no Company Job is created.")
    mattermost_test.add_argument("--message", required=True)
    mattermost_test.add_argument("--confirm", action="store_true")
    mattermost_test.add_argument("--json", action="store_true")
    mattermost_disable = channel_commands.add_parser("mattermost-disable", help="Remove only [mattermost_channel]; no Mattermost request is made.")
    mattermost_disable.add_argument("--json", action="store_true")
    matrix_status = channel_commands.add_parser("matrix-status", help="Show Matrix outbound readiness without contacting its homeserver.")
    matrix_status.add_argument("--json", action="store_true")
    matrix_configure = channel_commands.add_parser("matrix-configure", help="Configure one canonical Matrix room destination; it never contacts Matrix.")
    matrix_configure.add_argument("--homeserver-url", required=True)
    matrix_configure.add_argument("--room-id", required=True, help="Canonical Matrix !room:server identifier.")
    matrix_configure.add_argument("--token-env", default="MATRIX_ACCESS_TOKEN")
    matrix_configure.add_argument("--max-message-bytes", type=int, default=16_000)
    matrix_configure.add_argument("--timeout-seconds", type=float, default=15.0)
    matrix_configure.add_argument("--json", action="store_true")
    matrix_test = channel_commands.add_parser("matrix-test", help="Send one explicit Matrix plaintext event; no Company Job is created.")
    matrix_test.add_argument("--message", required=True)
    matrix_test.add_argument("--confirm", action="store_true")
    matrix_test.add_argument("--json", action="store_true")
    matrix_disable = channel_commands.add_parser("matrix-disable", help="Remove only [matrix_channel]; no Matrix request is made.")
    matrix_disable.add_argument("--json", action="store_true")
    matrix_inbox_status = channel_commands.add_parser("matrix-inbox-status", help="Show bounded Matrix plaintext intake readiness without connecting.")
    matrix_inbox_status.add_argument("--json", action="store_true")
    matrix_inbox_configure = channel_commands.add_parser("matrix-inbox-configure", help="Configure foreground allowlisted Matrix plaintext intake; it never contacts Matrix.")
    matrix_inbox_configure.add_argument("--workspace", type=Path, required=True)
    matrix_inbox_configure.add_argument("--homeserver-url", required=True)
    matrix_inbox_configure.add_argument("--room-id", required=True)
    matrix_inbox_configure.add_argument("--allow-sender", action="append", default=[], required=True, help="Canonical @user:server allowed to start a read-only Company Job; repeatable.")
    matrix_inbox_configure.add_argument("--token-env", default="MATRIX_ACCESS_TOKEN")
    matrix_inbox_configure.add_argument("--max-message-bytes", type=int, default=12_000)
    matrix_inbox_configure.add_argument("--max-messages-per-run", type=int, default=8)
    matrix_inbox_configure.add_argument("--timeout-seconds", type=float, default=30.0)
    matrix_inbox_configure.add_argument("--json", action="store_true")
    matrix_inbox_run = channel_commands.add_parser("matrix-inbox-run", help="Run one foreground Matrix sync batch; first successful sync only primes the cursor.")
    matrix_inbox_run.add_argument("--state", type=Path, default=None)
    matrix_inbox_run.add_argument("--max-messages", type=int, default=None)
    matrix_inbox_run.add_argument("--confirm", action="store_true")
    matrix_inbox_run.add_argument("--json", action="store_true")
    matrix_inbox_disable = channel_commands.add_parser("matrix-inbox-disable", help="Remove only [matrix_inbound]; it contacts no Matrix homeserver.")
    matrix_inbox_disable.add_argument("--json", action="store_true")
    mattermost_inbox_status = channel_commands.add_parser("mattermost-inbox-status", help="Show bounded Mattermost plaintext intake readiness without connecting.")
    mattermost_inbox_status.add_argument("--json", action="store_true")
    mattermost_inbox_configure = channel_commands.add_parser("mattermost-inbox-configure", help="Configure foreground allowlisted Mattermost plaintext intake; it never contacts Mattermost.")
    mattermost_inbox_configure.add_argument("--workspace", type=Path, required=True)
    mattermost_inbox_configure.add_argument("--base-url", required=True)
    mattermost_inbox_configure.add_argument("--channel-id", required=True)
    mattermost_inbox_configure.add_argument("--allow-sender", action="append", default=[], required=True, help="Mattermost user ID allowed to start a read-only Company Job; repeatable.")
    mattermost_inbox_configure.add_argument("--token-env", default="MATTERMOST_TOKEN")
    mattermost_inbox_configure.add_argument("--max-message-bytes", type=int, default=12_000)
    mattermost_inbox_configure.add_argument("--max-messages-per-run", type=int, default=8)
    mattermost_inbox_configure.add_argument("--timeout-seconds", type=float, default=20.0)
    mattermost_inbox_configure.add_argument("--json", action="store_true")
    mattermost_inbox_run = channel_commands.add_parser("mattermost-inbox-run", help="Run one foreground Mattermost post batch; first successful poll only primes the cursor.")
    mattermost_inbox_run.add_argument("--state", type=Path, default=None)
    mattermost_inbox_run.add_argument("--max-messages", type=int, default=None)
    mattermost_inbox_run.add_argument("--confirm", action="store_true")
    mattermost_inbox_run.add_argument("--json", action="store_true")
    mattermost_inbox_disable = channel_commands.add_parser("mattermost-inbox-disable", help="Remove only [mattermost_inbound]; it contacts no Mattermost server.")
    mattermost_inbox_disable.add_argument("--json", action="store_true")
    dingtalk_status = channel_commands.add_parser("dingtalk-status", help="Show DingTalk robot-webhook readiness without contacting DingTalk."); dingtalk_status.add_argument("--json", action="store_true")
    dingtalk_configure = channel_commands.add_parser("dingtalk-configure", help="Configure a named DingTalk static webhook environment; it never contacts DingTalk.")
    dingtalk_configure.add_argument("--webhook-env", default="DINGTALK_WEBHOOK_URL"); dingtalk_configure.add_argument("--max-message-bytes", type=int, default=4_000); dingtalk_configure.add_argument("--timeout-seconds",type=float,default=15.0); dingtalk_configure.add_argument("--json",action="store_true")
    dingtalk_test = channel_commands.add_parser("dingtalk-test", help="Send one explicit DingTalk robot markdown message; no Company Job is created.")
    dingtalk_test.add_argument("--message",required=True); dingtalk_test.add_argument("--title",default="Noruct channel test"); dingtalk_test.add_argument("--confirm",action="store_true"); dingtalk_test.add_argument("--json",action="store_true")
    dingtalk_disable=channel_commands.add_parser("dingtalk-disable",help="Remove only [dingtalk_channel]; no DingTalk request is made.");dingtalk_disable.add_argument("--json",action="store_true")
    teams_status = channel_commands.add_parser("teams-status", help="Show Teams workflow-webhook readiness without contacting Teams."); teams_status.add_argument("--json", action="store_true")
    teams_configure = channel_commands.add_parser("teams-configure", help="Configure one named Teams workflow-webhook environment; it never contacts Teams.")
    teams_configure.add_argument("--webhook-env", default="TEAMS_WEBHOOK_URL"); teams_configure.add_argument("--max-message-bytes", type=int, default=4_000); teams_configure.add_argument("--timeout-seconds", type=float, default=15.0); teams_configure.add_argument("--json", action="store_true")
    teams_test = channel_commands.add_parser("teams-test", help="Send one explicit Teams workflow-webhook text message; no Company Job is created.")
    teams_test.add_argument("--message", required=True); teams_test.add_argument("--confirm", action="store_true"); teams_test.add_argument("--json", action="store_true")
    teams_disable = channel_commands.add_parser("teams-disable", help="Remove only [teams_channel]; no Teams request is made."); teams_disable.add_argument("--json", action="store_true")
