"""Bounded company graph validation, staffing, scheduling, and replanning."""

from .graph import GraphValidationError, apply_patch, graph_from_proposal, ready_tasks
from .ledger import ActiveJobLedgerPort
from .models import (
    AttemptBudgetEvidence,
    AttemptFailureKind,
    CompanyRunRequest,
    EmployeeRecord,
    ExecutionReplicaAggregation,
    ExecutionReplicaPreference,
    ExecutionReplicaSpec,
    ExecutionReplicaStrategy,
    GraphPatch,
    GraphPatchExpectedImpact,
    GraphPatchEvent,
    GraphPatchObservedOutcome,
    GraphPatchProposalEvent,
    GraphPatchProposalStatus,
    GraphPatchValidationReceipt,
    GraphMutationLease,
    GraphPatchOperation,
    JobGraph,
    JobLimits,
    JobMetrics,
    JobResult,
    JobMutationEvent,
    JobStatus,
    JobTask,
    PatchOperationKind,
    PlanProposal,
    ReplanContext,
    SemanticOperation,
    TaskAssignmentEvent,
    TaskStatus,
    TaskAttemptRecord,
    TaskMutationType,
)
from .service import FirmKernel, ReplannerPort
from .workflow_shape import (
    MAX_CANONICAL_WORKFLOW_TASKS,
    WorkflowShapeError,
    canonical_workflow_shape,
)

__all__ = [
    "CompanyRunRequest",
    "ActiveJobLedgerPort",
    "AttemptBudgetEvidence",
    "AttemptFailureKind",
    "EmployeeRecord",
    "ExecutionReplicaAggregation",
    "ExecutionReplicaPreference",
    "ExecutionReplicaSpec",
    "ExecutionReplicaStrategy",
    "GraphPatch",
    "GraphPatchExpectedImpact",
    "GraphPatchEvent",
    "GraphPatchObservedOutcome",
    "GraphPatchProposalEvent",
    "GraphPatchProposalStatus",
    "GraphPatchValidationReceipt",
    "GraphMutationLease",
    "GraphPatchOperation",
    "GraphValidationError",
    "FirmKernel",
    "JobGraph",
    "JobMutationEvent",
    "JobLimits",
    "JobMetrics",
    "JobResult",
    "JobStatus",
    "JobTask",
    "MAX_CANONICAL_WORKFLOW_TASKS",
    "PatchOperationKind",
    "PlanProposal",
    "ReplanContext",
    "ReplannerPort",
    "SemanticOperation",
    "TaskAssignmentEvent",
    "TaskStatus",
    "TaskAttemptRecord",
    "TaskMutationType",
    "WorkflowShapeError",
    "apply_patch",
    "canonical_workflow_shape",
    "graph_from_proposal",
    "ready_tasks",
]
